framework:
    workflows: 
         projet_publishing:
            type: 'workflow' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'place'
            supports:
                - App\Entity\Projet
            initial_marking: draft
            places:
                - draft
                - reviewed
                - rejected
                - fini
            transitions:
                to_review:
                    from: draft
                    to:   reviewed
                publish:
                    from: reviewed
                    to:   fini
                reject:
                    from: reviewed
                    to:   rejected   
