<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190523084315 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'sqlite', 'Migration can only be executed safely on \'sqlite\'.');

        $this->addSql('CREATE TABLE IEI_MENU (idmen INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, MENCOD VARCHAR(50) DEFAULT NULL, MENLIB VARCHAR(100) DEFAULT NULL, MENORD DOUBLE PRECISION DEFAULT NULL, MENCOM VARCHAR(250) DEFAULT NULL, MENDAT DATE DEFAULT NULL, MENPHP VARCHAR(50) DEFAULT NULL, MENSQL VARCHAR(20) DEFAULT NULL)');
        $this->addSql('CREATE TABLE IEI_ONGLET (IDONG INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, IDSSM INTEGER DEFAULT NULL, ONGCOD VARCHAR(50) DEFAULT NULL, ONGLIB VARCHAR(100) DEFAULT NULL, ONGORD DOUBLE PRECISION DEFAULT NULL, ONGLEC DOUBLE PRECISION DEFAULT NULL, ONGCRE DOUBLE PRECISION DEFAULT NULL, ONGUPD DOUBLE PRECISION DEFAULT NULL, ONGADM DOUBLE PRECISION DEFAULT NULL, ONGCOM VARCHAR(250) DEFAULT NULL, ONGMAJ DATE DEFAULT NULL, ONGPHP VARCHAR(250) DEFAULT NULL, ONGSQL VARCHAR(200) DEFAULT NULL, ONGDEF DOUBLE PRECISION DEFAULT NULL, ONGSQLCRE VARCHAR(100) DEFAULT NULL, ONGSQLUPD VARCHAR(100) DEFAULT NULL, ONGSQLDEL VARCHAR(100) DEFAULT NULL, ONGCON DOUBLE PRECISION DEFAULT NULL, ONGSQLCON VARCHAR(250) DEFAULT NULL)');
        $this->addSql('CREATE TABLE IEI_SSMENU (idmen INTEGER DEFAULT NULL, IDSSM INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, SSMCOD VARCHAR(50) DEFAULT NULL, SSMLIB VARCHAR(100) DEFAULT NULL, SSMORD DOUBLE PRECISION DEFAULT NULL, SSMCOM VARCHAR(250) DEFAULT NULL, SSMMAJ DATE DEFAULT NULL, SSMPHP VARCHAR(250) DEFAULT NULL)');
        $this->addSql('CREATE INDEX IDX_691285B514CB09BB ON IEI_SSMENU (idmen)');
        $this->addSql('CREATE TABLE iei_champs (idong INTEGER DEFAULT NULL, IDCHP INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, CHPLIB VARCHAR(50) DEFAULT NULL, CHPCHA VARCHAR(20) DEFAULT NULL, CHPORD DOUBLE PRECISION DEFAULT NULL, CHPLON DOUBLE PRECISION DEFAULT NULL, CHPTYP VARCHAR(20) DEFAULT NULL, CHPSAI DOUBLE PRECISION DEFAULT NULL, CHPSEL VARCHAR(500) DEFAULT NULL, CHPREC DOUBLE PRECISION DEFAULT NULL)');
        $this->addSql('CREATE INDEX IDX_C03171F48D67BCBA ON iei_champs (idong)');
        $this->addSql('CREATE TABLE champ (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, onglet_id INTEGER DEFAULT NULL, chpcha VARCHAR(255) DEFAULT NULL, chpord INTEGER DEFAULT NULL, chplon INTEGER DEFAULT NULL, chptyp VARCHAR(255) NOT NULL, chpsai INTEGER DEFAULT NULL, chpsel VARCHAR(255) DEFAULT NULL, chprec INTEGER DEFAULT NULL, chplib VARCHAR(255) DEFAULT NULL)');
        $this->addSql('CREATE INDEX IDX_2F61E0ADBD1A86CC ON champ (onglet_id)');
        $this->addSql('CREATE TABLE onglet (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ssmenu_id INTEGER DEFAULT NULL, ongcod VARCHAR(255) DEFAULT NULL, onglib VARCHAR(255) DEFAULT NULL, ongord INTEGER DEFAULT NULL, onglec INTEGER DEFAULT NULL, ongcre INTEGER DEFAULT NULL, ongupd INTEGER DEFAULT NULL, ongadm INTEGER DEFAULT NULL, ongcom VARCHAR(255) DEFAULT NULL, ongmaj DATETIME DEFAULT NULL, ongphp VARCHAR(255) DEFAULT NULL, ongsql VARCHAR(255) DEFAULT NULL, ongdef INTEGER DEFAULT NULL, ongsqlcre VARCHAR(255) DEFAULT NULL, ongsqlupd VARCHAR(255) DEFAULT NULL, ongsqldel VARCHAR(255) DEFAULT NULL, ongcon INTEGER DEFAULT NULL)');
        $this->addSql('CREATE INDEX IDX_C6BC02395C434BA1 ON onglet (ssmenu_id)');
        $this->addSql('CREATE TABLE menu (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, mencod VARCHAR(255) DEFAULT NULL, menlib VARCHAR(255) DEFAULT NULL, menord INTEGER DEFAULT NULL, mencom VARCHAR(255) DEFAULT NULL, mendat DATETIME DEFAULT NULL, menphp VARCHAR(255) DEFAULT NULL, mensql VARCHAR(255) DEFAULT NULL)');
        $this->addSql('CREATE TABLE ssmenu (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, menu_id INTEGER NOT NULL, ssmcod VARCHAR(255) DEFAULT NULL, ssmlib VARCHAR(255) DEFAULT NULL, ssmord INTEGER DEFAULT NULL, ssmcom VARCHAR(255) DEFAULT NULL, ssmmaj DATETIME DEFAULT NULL, ssmphp VARCHAR(255) DEFAULT NULL)');
        $this->addSql('CREATE INDEX IDX_DE47A15CCCD7E912 ON ssmenu (menu_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'sqlite', 'Migration can only be executed safely on \'sqlite\'.');

        $this->addSql('DROP TABLE IEI_MENU');
        $this->addSql('DROP TABLE IEI_ONGLET');
        $this->addSql('DROP TABLE IEI_SSMENU');
        $this->addSql('DROP TABLE iei_champs');
        $this->addSql('DROP TABLE champ');
        $this->addSql('DROP TABLE onglet');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE ssmenu');
    }
}
